kakiage_date:
  url: /kakiage/:year/:month/:day
  param: { module: kakiage, action: index }
  requirements:
    year:  "[12][0-9]{3}"
    month: "(0?[1-9])|(1[0-2])"
    day:   "(0?[1-9])|([12][0-9])|(3[01])"
